### ISSUE TITLE
if robot slowly roate, why imu data do not change.

### ISSUE THREAD

**Issue by 1chick** [larics/ros_lpms_imu#15]
if robot slowly roate, why lpms imu data do not change. i cannot copy with it , somebody help me please
my device model is LPMS UTTL2.

**Comment by dmiklic** [comment]
Please provide some more details.

1) Which data exactly are you looking at? Velocity? Acceleration?
2) How do you know that it does not change, i.e., how are you observing the data? With `rostopic echo` or are you plotting it?
3) How slowly is the robot actually rotating? If it is  _very_ slow, than it is to be expected that velocity and acceleration changes will be minimal.
4) Do you observe the same behaviour when monitoring the data in the LPMS Windows GUI application?

**Comment by 1chick** [comment]
@dmiklic 
thank your so soon reply。
1. i just look at imu_msg.orientation.w
2. i open rviz observe the imu/data topic, set box show
3.i control the robot as 0.4 rad/s rotation, but imu_msg.orientation.w data keep not change,i set 0.7 rad/s make change, 
4.also i use LPMS windows GUI application check it , it got same reuslt .

i think whether or not change some params.

**Comment by dmiklic** [comment]
You should look at imu_msg.angular_velocity as that part of the message holds information about the speed of robot rotation.

Looking only at imu_msg.orientation.w is not a good indication of anything, as this is only one component of the orientation quaternion, i.e., not all changes in orientation will have a major impact on this particular component.

If the behavior is the same as when you use the Windows GUI application, I'd say that there is nothing wrong with your ROS setup. You cahn also try to visualize what is really going on using [rviz_imu_plugin](http://wiki.ros.org/rviz_imu_plugin).

**Comment by 1chick** [comment]
@dmiklic 
yes i look at angular_velociy is normal, the value keeps some little change,(i,e, 0.3399rad/s),maybe accelermeter is zero, but i change it keeps 0.7rad/s almost i can get orientation.w is changed, and if accelermeter  change   orientation.w is normal.

**Comment by dmiklic** [comment]
This sounds like normal behavior to me, but maybe there are some sensitivity issues. Maybe @TobiSchluter can share some more insight.

**Comment by TobiSchluter** [comment]
I pointed our sensor guys to this thread but please don't hesitate to contact us as indicated [on our webpage](http://www.lp-research.com/). That makes it easier for us to reference the calibration documentation we kept on your sensor etc.  There are a variety of settings affecting the orientation integration, please see [our manual ](https://www.lp-research.com/site/wp-content/uploads/2012/05/LpmsAllUsersGuide1.3.4.pdf) following p. 28 and let us know if any of the settings help.

In general, if you have requests concerning the sensors this is not the right place. dmiklic _et al_ were kind enough to share their ROS driver with the world but your issue seems to be with the LpSensor library or the sensor itself. We all love it when somebody else does our work, but when we're asked to do somebody else's work our feelings usually are less bright :-)

Looking forward to hearing from you.

**Comment by TobiSchluter** [comment]
ps my colleagues seem to agree that your issue sounds like the gyroscope autocalibration kicking in because the sensor thinks it is at rest. You can turn this off in LpmsControl as indicated in the screenshot you find below:
![Screenshot](https://user-images.githubusercontent.com/11887541/27065066-03eedbcc-5036-11e7-909a-07aae534c9be.jpg)  Alternatively, you can use the LpSensor library to achieve the desired effect.

Documentation for the autocalibration can be found on p. 30 of the manual.

**Comment by 1chick** [comment]
@TobiSchluter
yes i can check it changed when slowly move. thanks

**Comment by TobiSchluter** [comment]
@1chick 
Good to hear. If there are any other questions, please feel free to contact us.
